# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved. # noqa: E501
# SPDX-License-Identifier: Apache-2.0

"""Emit the QED SMARTS and ADS constant tables as a C++ header.

The tables are transcribed from ``rdkit.Chem.QED`` rather than retyped, so the C++
descriptor stays in step with the RDKit release it was generated against. Run this
when bumping RDKit and diff the result::

    python tools/generate_qed_data.py > src/qed_data.h
"""

import sys

from rdkit import __version__ as rdkit_version
from rdkit.Chem import QED

# The order QED.QEDproperties declares, which is also the order of the weights.
PROPERTY_ORDER = ("MW", "ALOGP", "HBA", "HBD", "PSA", "ROTB", "AROM", "ALERTS")


def _cxx_string(text: str) -> str:
    """Render a SMARTS string as a C++ string literal."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    """Write the header to stdout."""
    out = sys.stdout.write

    out(
        "// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION"
        " & AFFILIATES. All rights reserved.\n"
        "// SPDX-License-Identifier: Apache-2.0\n\n"
        "//! @file Generated by tools/generate_qed_data.py -- do not edit by hand.\n"
        f"//!       Transcribed from rdkit.Chem.QED of RDKit {rdkit_version}.\n\n"
        "#pragma once\n\n"
        "#include <array>\n\n"
        "namespace cuik_molmaker::qed_data {\n\n"
    )

    out("//! SMARTS matching an aliphatic ring atom bonded to a non-aromatic atom.\n")
    out(
        "inline constexpr const char* ALIPHATIC_RINGS_SMARTS = "
        f"{_cxx_string('[$([A;R][!a])]')};\n\n"
    )

    out("//! Acceptor patterns; QED's HBA term counts all of their matches.\n")
    out(
        f"inline constexpr std::array<const char*, {len(QED.AcceptorSmarts)}>"
        " ACCEPTOR_SMARTS = {\n"
    )
    for smarts in QED.AcceptorSmarts:
        out(f"  {_cxx_string(smarts)},\n")
    out("};\n\n")

    out("//! Alert patterns; QED's ALERTS term counts how many match at all.\n")
    out(
        f"inline constexpr std::array<const char*, {len(QED.StructuralAlertSmarts)}>"
        " STRUCTURAL_ALERT_SMARTS = {\n"
    )
    for smarts in QED.StructuralAlertSmarts:
        out(f"  {_cxx_string(smarts)},\n")
    out("};\n\n")

    out("//! Asymmetric double sigmoidal parameters (a..f, dmax) per QED property.\n")
    out(
        f"inline constexpr std::array<std::array<double, 7>, {len(PROPERTY_ORDER)}>"
        " ADS_PARAMETERS = {{\n"
    )
    for name in PROPERTY_ORDER:
        values = ", ".join(repr(float(v)) for v in QED.adsParameters[name])
        # The name goes above the row so no line exceeds the project's 120-column limit.
        out(f"  // {name}\n  {{{{{values}}}}},\n")
    out("}};\n\n")

    weights = ", ".join(repr(float(w)) for w in QED.WEIGHT_MEAN)
    out("//! QED weights_mean, in PROPERTY_ORDER.\n")
    out(
        f"inline constexpr std::array<double, {len(PROPERTY_ORDER)}>"
        f" WEIGHT_MEAN = {{{weights}}};\n\n"
    )

    out("}  // namespace cuik_molmaker::qed_data\n")


if __name__ == "__main__":
    main()
